default-stats:
 HEALTH:
  default: 100
  min: 5
  max: 1000

  SPEED:
   default: 100
   min: -100
   max: 600

  DEFENSE:
   default: 0
   min: -100000
   max: 100000

  INTELLIGENCE:
   default: 100
   min: 0
   max: 10000

 STRENGTH:
  default: 10
  min: 0
  max: 10000

 WEAPON_DAMAGE:
  default: 0
  min: 0
  max: 5000

 HEALTH_REGENERATION:
  default: 5
  min: 0
  max: 500

 VITALITY:
  default: 0
  min: 0
  max: 100

 KNOCKBACK_RESISTANCE:
  default: 0
  min: -20
  max: 20

 KNOCKBACK:
  default: 2
  min: -20
  max: 20

 FALL_DAMAGE_RESISTANCE:
  default: 0
  min: -100
  max: 100

  FIRE_RESISTANCE:
   default: 0
   min: -100
   max: 100