default-stats:
 HEALTH:
  default: 100
  min: 5
  max: 1000

 DAMAGE:
  default: 15
  min: 0
  max: 500

 HEALTH_REGENERATION:
  default: 5
  min: 0
  max: 500

 VITALITY:
  default: 0
  min: 0
  max: 100

 KNOCKBACK_RESISTANCE:
  default: 0
  min: -20
  max: 20

 KNOCKBACK:
  default: 2
  min: -20
  max: 20

 FALL_DAMAGE_RESISTANCE:
  default: 0
  min: -100
  max: 100

  FIRE_RESISTANCE:
   default: 0
   min: -100
   max: 100