name: Asgardus
version: '1.0'
main: ahjd.asgardus.Asgardus
api-version: '1.21'
authors: [ahjd]

commands:
  stats:
    description: Manage player stats
    usage: /stats [set|add|reset] <stat> <amount> [player]