package ahjd.asgardus.statserivce.utils;

public enum StatType {
    HEALTH,
    WEAPON_DAMAGE,
    STRENGTH,
    INTELLIGENCE,
    SPEED,
    DEFENSE,
    DAMAGE,
    CURRENT_HEALTH,
    HEALTH_REGENERATION,
    VITALITY,
    KNOCKBACK,
    KNOCKBACK_RESISTANCE,
    FALL_DAMAGE_RESISTANCE,
    FIRE_RESISTANCE
}
